# Generated by Django 4.2.4 on 2023-12-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cat_data',
            new_name='cat_id',
        ),
    ]
