# Generated by Django 4.2.4 on 2024-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_rename_cat_data_products_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='qty',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
