# Generated by Django 4.2.4 on 2024-01-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_products_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qty',
        ),
    ]
