# Generated by Django 4.2.4 on 2024-01-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_remove_products_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('product', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='userside.products')),
            ],
        ),
    ]
