# Generated by Django 4.2.4 on 2024-01-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_rename_name_review_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='email',
            new_name='user_email',
        ),
    ]
