# Generated by Django 4.2.4 on 2024-01-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_review_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='UserSideReview',
        ),
    ]
