# Generated by Django 4.2.4 on 2024-01-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_rename_review_usersidereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersidereview',
            old_name='user_email',
            new_name='email',
        ),
    ]
