# Generated by Django 4.2.4 on 2024-01-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='UserSideRevieweview',
        ),
    ]
