# Generated by Django 4.2.4 on 2024-01-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_rename_review_usersiderevieweview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSideRevieweview',
            new_name='UserSideReview',
        ),
    ]
