# Generated by Django 4.2.4 on 2024-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0014_rename_usersiderevieweview_usersidereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersidereview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
