# Generated by Django 4.2.4 on 2024-01-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0015_alter_usersidereview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersidereview',
            old_name='rating',
            new_name='rat',
        ),
    ]
