# Generated by Django 4.2.4 on 2024-01-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0016_rename_rating_usersidereview_rat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersidereview',
            old_name='rat',
            new_name='rating',
        ),
    ]
