# Generated by Django 4.2.4 on 2024-01-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0017_rename_rat_usersidereview_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSideReview',
            new_name='review',
        ),
    ]
