# Generated by Django 4.2.4 on 2024-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0018_rename_usersidereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
