# Generated by Django 4.2.4 on 2024-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0019_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
