# Generated by Django 4.2.4 on 2024-01-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0020_products_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userside.products')),
            ],
        ),
    ]
